import { Bill } from '../types';

/**
 * Formats a Date or ISO string into iCalendar date format (YYYYMMDD for all-day events).
 */
function formatIcsDate(dateStr?: string): { start: string; end: string } {
  let date: Date;

  if (dateStr) {
    // Parse YYYY-MM-DD or ISO
    const parts = dateStr.split('-');
    if (parts.length === 3) {
      date = new Date(parseInt(parts[0], 10), parseInt(parts[1], 10) - 1, parseInt(parts[2], 10));
    } else {
      date = new Date(dateStr);
    }
  } else {
    // Default to today + 14 days if no date
    date = new Date();
    date.setDate(date.getDate() + 14);
  }

  if (isNaN(date.getTime())) {
    date = new Date();
  }

  const pad = (n: number) => (n < 10 ? `0${n}` : `${n}`);

  const startYear = date.getFullYear();
  const startMonth = pad(date.getMonth() + 1);
  const startDay = pad(date.getDate());
  const start = `${startYear}${startMonth}${startDay}`;

  // Next day for inclusive all-day event in RFC 5545
  const nextDate = new Date(date.getTime());
  nextDate.setDate(nextDate.getDate() + 1);
  const endYear = nextDate.getFullYear();
  const endMonth = pad(nextDate.getMonth() + 1);
  const endDay = pad(nextDate.getDate());
  const end = `${endYear}${endMonth}${endDay}`;

  return { start, end };
}

/**
 * Format current timestamp in UTC (YYYYMMDDTHHMMSSZ).
 */
function getTimestampNow(): string {
  const now = new Date();
  const pad = (n: number) => (n < 10 ? `0${n}` : `${n}`);
  return (
    now.getUTCFullYear().toString() +
    pad(now.getUTCMonth() + 1) +
    pad(now.getUTCDate()) +
    'T' +
    pad(now.getUTCHours()) +
    pad(now.getUTCMinutes()) +
    pad(now.getUTCSeconds()) +
    'Z'
  );
}

/**
 * Escapes characters for iCalendar text fields according to RFC 5545.
 */
function escapeIcsText(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\r?\n/g, '\\n');
}

/**
 * Generates an RFC 5545 compliant .ics calendar content string for an array of Bills.
 */
export function generateIcsCalendar(bills: Bill[], calendarName = 'RevenueFlow Payment Due Dates'): string {
  const dtStamp = getTimestampNow();

  const events = bills.map((bill) => {
    const { start, end } = formatIcsDate(bill.dueDate || bill.date);
    const uid = `rf-bill-${bill.id || bill.billNumber}-${start}@revenueflow.io`;
    const summary = escapeIcsText(
      `Payment Due: ${bill.billNumber} (${bill.currency}${bill.total.toLocaleString(undefined, {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2
      })}) - ${bill.customerName}`
    );

    const itemsList = bill.items
      .map((item) => `- ${item.name} (${item.quantity}x @ ${bill.currency}${item.rate.toFixed(2)})`)
      .join('\n');

    const description = escapeIcsText(
      `Invoice Number: ${bill.billNumber}\n` +
      `Customer: ${bill.customerName}\n` +
      `Amount Due: ${bill.currency}${bill.total.toLocaleString(undefined, { minimumFractionDigits: 2 })}\n` +
      `Payment Status: ${bill.status.toUpperCase()}\n` +
      `Invoice Date: ${bill.date}\n` +
      `Due Date: ${bill.dueDate || 'Immediate'}\n` +
      `Billing Type: ${bill.type === 'gst' ? 'Tax Invoice (GST)' : 'Standard Estimate (Raw)'}\n` +
      `Customer Phone: ${bill.phoneNumber}\n\n` +
      `Line Items:\n${itemsList}\n\n` +
      `Generated by RevenueFlow Financial Operations`
    );

    const status = bill.status === 'paid' ? 'CANCELLED' : 'CONFIRMED';

    return [
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${dtStamp}`,
      `DTSTART;VALUE=DATE:${start}`,
      `DTEND;VALUE=DATE:${end}`,
      `SUMMARY:${summary}`,
      `DESCRIPTION:${description}`,
      `STATUS:${status}`,
      'TRANSP:TRANSPARENT',
      'CATEGORIES:Finance,Invoicing,Payments,Accounts Receivable',
      'BEGIN:VALARM',
      'ACTION:DISPLAY',
      `DESCRIPTION:${escapeIcsText(`Reminder: Payment Due for ${bill.billNumber} (${bill.customerName})`)}`,
      'TRIGGER:-P1D',
      'END:VALARM',
      'BEGIN:VALARM',
      'ACTION:DISPLAY',
      `DESCRIPTION:${escapeIcsText(`Payment Due Today: ${bill.billNumber} (${bill.currency}${bill.total.toFixed(2)})`)}`,
      'TRIGGER:PT9H',
      'END:VALARM',
      'END:VEVENT'
    ].join('\r\n');
  });

  const icsLines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//RevenueFlow//Financial Operations Calendar v1.0//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${calendarName}`,
    'X-WR-TIMEZONE:UTC',
    ...events,
    'END:VCALENDAR'
  ];

  return icsLines.join('\r\n');
}

/**
/**
 * Triggers a download of an .ics file in the browser (Desktop & Mobile safe).
 */
export function downloadIcsFile(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const cleanFilename = filename.endsWith('.ics') ? filename : `${filename}.ics`;

  const isIOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !(window as any).MSStream;
  if (isIOS) {
    const win = window.open(url, '_blank');
    if (!win) {
      window.location.href = url;
    }
  } else {
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', cleanFilename);
    link.setAttribute('target', '_blank');
    link.setAttribute('rel', 'noopener noreferrer');
    link.style.display = 'none';
    document.body.appendChild(link);
    link.click();
    setTimeout(() => {
      if (document.body.contains(link)) {
        document.body.removeChild(link);
      }
      setTimeout(() => URL.revokeObjectURL(url), 10000);
    }, 500);
  }
}

/**
 * Helper to export payment due dates for multiple bills.
 */
export function exportBillsPaymentDueDates(
  bills: Bill[],
  filenamePrefix = 'RevenueFlow_Payment_Due_Dates'
): { count: number; filename: string } {
  const filteredBills = bills.filter((b) => b.dueDate || b.date);
  const filename = `${filenamePrefix}_${new Date().toISOString().slice(0, 10)}.ics`;
  const icsContent = generateIcsCalendar(
    filteredBills,
    'RevenueFlow Invoice Due Dates'
  );
  downloadIcsFile(icsContent, filename);
  return { count: filteredBills.length, filename };
}

/**
 * Helper to export a single bill's payment due date.
 */
export function exportSingleBillDueDate(bill: Bill): string {
  const filename = `Due_${bill.billNumber}_${bill.customerName.replace(/[^a-zA-Z0-9]/g, '_')}.ics`;
  const icsContent = generateIcsCalendar(
    [bill],
    `Due Date: ${bill.billNumber}`
  );
  downloadIcsFile(icsContent, filename);
  return filename;
}
